---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: vendor
    contents:
      - path: .
        githubRelease:
          slug: emqx/emqx-operator
          tag: "2.3.1"
          assetNames:
            - install.yaml
          disableAutoChecksumValidation: true
