---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: vendor
    contents:
      - path: .
        git:
          url: https://github.com/mogenius/renovate-operator
          ref: "4.8.1"
          skipInitSubmodules: true
        includePaths:
          - charts/renovate-operator/crd/*.yaml
