---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: vendor
    contents:
      - path: .
        git:
          url: https://github.com/cilium/cilium
          ref: v1.19.4
          skipInitSubmodules: true
        includePaths:
          - pkg/k8s/apis/cilium.io/client/crds/v2/*.yaml
          - pkg/k8s/apis/cilium.io/client/crds/v2alpha1/*.yaml
