---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: vendor
    contents:
      - path: .
        git:
          url: https://github.com/openebs/lvm-localpv
          ref: v1.9.0
          skipInitSubmodules: true
        includePaths:
          - deploy/yamls/*-crd.yaml
