---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: vendor
    contents:
      - path: .
        githubRelease:
          slug: kedacore/keda
          tag: v2.19.0
          assetNames:
            - keda-*-crds.yaml
          disableAutoChecksumValidation: true
