---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: vendor
    contents:
      - path: .
        git:
          url: https://github.com/gravitational/teleport
          ref: v18.8.1
          # teleport.e is a private enterprise submodule we can't (and don't
          # need to) clone for CRD extraction.
          skipInitSubmodules: true
        includePaths:
          - integrations/operator/config/crd/bases/*.yaml
