---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: vendor
    contents:
      - path: .
        git:
          url: https://github.com/dragonflydb/dragonfly-operator
          ref: v1.5.0
          skipInitSubmodules: true
        includePaths:
          - manifests/crd.yaml
