---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: vendor
    contents:
      - path: .
        githubRelease:
          slug: open-telemetry/opentelemetry-operator
          tag: v0.151.0
          assetNames:
            - opentelemetry-operator.yaml
          disableAutoChecksumValidation: true
