---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: vendor
    contents:
      - path: .
        git:
          url: https://github.com/fluent/fluent-operator
          ref: v3.7.0
          skipInitSubmodules: true
        includePaths:
          - config/crd/bases/*.yaml
