---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: vendor
    contents:
      - path: .
        git:
          url: https://github.com/rook/rook
          ref: v1.19.5
          skipInitSubmodules: true
        includePaths:
          - deploy/examples/crds.yaml
          - deploy/olm/assemble/objectbucket.io_*.yaml
