---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: vendor
    contents:
      - path: .
        git:
          url: https://github.com/kubernetes-sigs/node-feature-discovery
          ref: v0.18.3
          skipInitSubmodules: true
        includePaths:
          - deployment/base/nfd-crds/nfd-api-crds.yaml
          - deployment/base/noderesourcetopologies-crd/noderesourcetopologies.yaml
