---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: vendor
    contents:
      - path: .
        githubRelease:
          slug: VictoriaMetrics/operator
          tag: v0.70.1
          assetNames:
            - crd.yaml
          disableAutoChecksumValidation: true
