---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: vendor
    contents:
      - path: .
        git:
          url: https://github.com/longhorn/longhorn-manager
          ref: v1.11.2
          skipInitSubmodules: true
        includePaths:
          - k8s/crds.yaml
